#This is the Bitwise program to check
print ("Welcome to Addition Calculator")
print ("Enter the value A")
a = int(input())
print ("Enter the value B")
b = int(input())
and_val = (a & b)
or_val = (a | b)
xor_val = (a ^ b)
#not_val = (a ~ b)
left_val = (a << b)
right_val = (a >> b)
print ("The value of A is ", a )
print ("The value of B is ", b )
print ("The value of AND is", and_val)
print ("The value of OR is", or_val)
print ("The value of XOR is", xor_val)
#print ("The value of not is", not_val)
print ("The value of left is", left_val)
print ("The value of right is", right_val)

